#!/bin/bash
# verify_all.sh - Master verification pipeline
# Part of Phase 3: Verification Pipeline
# Orchestrates all 72-KPI verification checks

set -euo pipefail

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
REPORT_DIR="./verification-reports"
TIMESTAMP_DIR="$REPORT_DIR/$TIMESTAMP"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=========================================="
echo "72-KPI VERIFICATION PIPELINE"
echo "Allbright DeFi V91"
echo "Timestamp: $TIMESTAMP"
echo "=========================================="
echo ""

# Create timestamped report directory
mkdir -p "$TIMESTAMP_DIR"

# Track overall status
OVERALL_STATUS=0

# Phase 3.1: Module Registry Verification
echo -e "${BLUE}[1/4] Running Module Registry Verification...${NC}"
if bash scripts/verify_modules.sh > "$TIMESTAMP_DIR/module-verification.log" 2>&1; then
  echo -e "${GREEN}✅ Module registry verification PASSED${NC}"
else
  echo -e "${RED}❌ Module registry verification FAILED${NC}"
  OVERALL_STATUS=1
fi
echo ""

# Phase 3.2: Module Compilation Check
echo -e "${BLUE}[2/4] Checking Module Compilation...${NC}"
if [ -d "backend" ] && [ -f "backend/Cargo.toml" ]; then
  cd backend
  if cargo check --quiet 2>&1 | tee "../$TIMESTAMP_DIR/compilation-check.log"; then
    echo -e "${GREEN}✅ All modules compile successfully${NC}"
  else
    echo -e "${RED}❌ Compilation errors detected${NC}"
    OVERALL_STATUS=1
  fi
  cd ..
else
  echo -e "${YELLOW}⚠️  Backend directory not found, skipping compilation check${NC}"
fi
echo ""

# Phase 3.3: KPI Evidence Verification
echo -e "${BLUE}[3/4] Running KPI Evidence Verification...${NC}"
if [ -f "KPIS_VERIFICATION_TABLE.md" ]; then
  if bash scripts/verify_kpi_evidence.sh > "$TIMESTAMP_DIR/evidence-verification.log" 2>&1; then
    echo -e "${GREEN}✅ KPI evidence verification PASSED${NC}"
  else
    echo -e "${RED}❌ KPI evidence verification FAILED${NC}"
    OVERALL_STATUS=1
  fi
else
  echo -e "${YELLOW}⚠️  KPIS_VERIFICATION_TABLE.md not found, skipping evidence check${NC}"
fi
echo ""

# Phase 3.4: Baseline Estimator Tests
echo -e "${BLUE}[4/4] Running Baseline Estimator Tests...${NC}"
if [ -f "backend/kpi_telemetry.rs" ]; then
  cd backend
  if cargo test --quiet kpi_telemetry 2>&1 | tee "../$TIMESTAMP_DIR/baseline-tests.log"; then
    echo -e "${GREEN}✅ Baseline estimator tests PASSED${NC}"
  else
    echo -e "${RED}❌ Baseline estimator tests FAILED${NC}"
    OVERALL_STATUS=1
  fi
  cd ..
else
  echo -e "${YELLOW}⚠️  kpi_telemetry.rs not found, skipping baseline tests${NC}"
fi
echo ""

# Generate master verification report
echo "=========================================="
echo "Generating Master Verification Report..."
echo "=========================================="

cat > "$TIMESTAMP_DIR/VERIFICATION-REPORT.md" << EOF
# 72-KPI Verification Report

**Timestamp:** $TIMESTAMP
**System:** Allbright DeFi V91
**Verification Pipeline:** v1.0

## Summary

| Check | Status | Details |
|-------|--------|---------|
| Module Registry | $(if [ $OVERALL_STATUS -eq 0 ]; then echo "✅ PASS"; else echo "❌ FAIL"; fi) | See module-verification.log |
| Compilation | $(if [ $OVERALL_STATUS -eq 0 ]; then echo "✅ PASS"; else echo "❌ FAIL"; fi) | See compilation-check.log |
| Evidence Gate | $(if [ $OVERALL_STATUS -eq 0 ]; then echo "✅ PASS"; else echo "❌ FAIL"; fi) | See evidence-verification.log |
| Baseline Tests | $(if [ $OVERALL_STATUS -eq 0 ]; then echo "✅ PASS"; else echo "❌ FAIL"; fi) | See baseline-tests.log |

## Overall Status

$(if [ $OVERALL_STATUS -eq 0 ]; then
  echo "**✅ ALL VERIFICATION CHECKS PASSED**"
  echo ""
  echo "The 72-KPI verification architecture is fully operational."
  echo "All modules registered, evidence validated, and baselines computed."
else
  echo "**❌ VERIFICATION FAILED**"
  echo ""
  echo "One or more checks failed. Review individual logs for details."
fi)

## Artifacts

- Module registry log: \`module-verification.log\`
- Compilation log: \`compilation-check.log\`
- Evidence log: \`evidence-verification.log\`
- Baseline test log: \`baseline-tests.log\`

## Next Steps

$(if [ $OVERALL_STATUS -eq 0 ]; then
  echo "1. Proceed to Phase 4: Engine Mode Re-articulation"
  echo "2. Update BUSINESS_PLAN_FULL.md engine mode specifications"
  echo "3. Remove capital percentages from mode descriptions"
else
  echo "1. Review failed checks in detail logs"
  echo "2. Fix compilation errors or missing evidence"
  echo "3. Re-run verification pipeline"
fi)

---

**Generated by:** verify_all.sh
**Pipeline Version:** 1.0
EOF

echo ""
echo "=========================================="
echo "Master report generated: $TIMESTAMP_DIR/VERIFICATION-REPORT.md"
echo "=========================================="
echo ""

if [ $OVERALL_STATUS -eq 0 ]; then
  echo -e "${GREEN}✅ ALL VERIFICATION CHECKS PASSED${NC}"
  echo "The 72-KPI verification architecture is ready for deployment."
  exit 0
else
  echo -e "${RED}❌ VERIFICATION PIPELINE FAILED${NC}"
  echo "Review logs in $TIMESTAMP_DIR for details."
  exit 1
fi